services:
  - type: web
    name: deepfake-detection
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 120 project_settings.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 8000
      - key: DEBUG
        value: 'False'
